<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[navegamos a la url: http://192.168.13.142/NomifacilTest/Default.aspx]]>
    </line>
    <line>
      <![CDATA[Se ingresa el usuario denisse@mltic.com]]>
    </line>
    <line>
      <![CDATA[Se ingresa el password gobdigital2]]>
    </line>
    <line>
      <![CDATA[Se da clic en ingresar ]]>
    </line>
    <line>
      <![CDATA[<img src='C:\Users\molvera\Documents\selenium\ScreenShoot\IMAGE_NO1_2018_05_28 18_43_24.png'/>]]>
    </line>
    <line>
      <![CDATA[<img src='C:\Users\molvera\Documents\selenium\ScreenShoot\IMAGE_NO2_2018_05_28 18_43_27.png'/>]]>
    </line>
  </reporter-output>
  <suite started-at="2018-05-28T23:43:20Z" name="Default suite" finished-at="2018-05-28T23:43:27Z" duration-ms="7505">
    <groups>
    </groups>
    <test started-at="2018-05-28T23:43:20Z" name="Default test" finished-at="2018-05-28T23:43:27Z" duration-ms="7505">
      <class name="automationFramework.EjecutaPrueba">
        <test-method signature="Login()[pri:1, instance:automationFramework.EjecutaPrueba@76ed1b7c]" started-at="2018-05-28T23:43:20Z" name="Login" description="Este caso demuestra los pasos para acceder al sistema de nomina" finished-at="2018-05-28T23:43:27Z" duration-ms="7465" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[navegamos a la url: http://192.168.13.142/NomifacilTest/Default.aspx]]>
            </line>
            <line>
              <![CDATA[Se ingresa el usuario denisse@mltic.com]]>
            </line>
            <line>
              <![CDATA[Se ingresa el password gobdigital2]]>
            </line>
            <line>
              <![CDATA[Se da clic en ingresar ]]>
            </line>
            <line>
              <![CDATA[<img src='C:\Users\molvera\Documents\selenium\ScreenShoot\IMAGE_NO1_2018_05_28 18_43_24.png'/>]]>
            </line>
            <line>
              <![CDATA[<img src='C:\Users\molvera\Documents\selenium\ScreenShoot\IMAGE_NO2_2018_05_28 18_43_27.png'/>]]>
            </line>
          </reporter-output>
        </test-method> <!-- Login -->
        <test-method signature="case2()[pri:2, instance:automationFramework.EjecutaPrueba@76ed1b7c]" started-at="2018-05-28T23:43:27Z" name="case2" description="este es un segundo caso vacio" finished-at="2018-05-28T23:43:27Z" duration-ms="4" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [12] but found [11]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [12] but found [11]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at automationFramework.EjecutaPrueba.case2(EjecutaPrueba.java:108)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- case2 -->
      </class> <!-- automationFramework.EjecutaPrueba -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
